### ISSUE TITLE
翻译文本替换问题

### ISSUE THREAD

**Issue by godadom** [chinosk6/gakuen-imas-localify#13]
请问为什么翻译过的文本不会被替换上，只留下空白呢？
![Screenshot_2024-06-04-21-53-38-321_com bandainamcoent idolmaster_gakuen](https://github.com/chinosk6/gakuen-imas-localify/assets/110595879/569bdcf9-7750-4005-92fc-97bc7123e017)

这是我的apk：
Downloads/app-debug/assets 
➜ tree . 
.
├── gakumas-local
│   ├── README.md
│   ├── local-files
│   │   ├── MO-UDShinGo-SC-Gb4-M.otf
│   │   ├── generic.json
│   │   ├── localization.json
│   │   └── resource
│   │       └── adv_dear_fktn_001.txt
│   │       └── adv_dear_fktn_002.txt
│   │       └── ......
│   ├── merge.py
│   ├── requirements.txt
│   └── version.txt
└── xposed_init

> version.txt 记录翻译版本号。每次插件启动都会检查 asset 内的版本和本地的版本是否一致。不一致会覆盖文件到 /data/data/com.bandainamcoent.idolmaster_gakuen/files/gakumas-lical/ 文件夹内

难道是version不对吗？

附上我打包前的仓库：https://github.com/godadom/imas-localify

**Comment by chinosk6** [comment]
测试了你仓库内 Action 的 APK，在我的设备上能正常运行，翻译一切正常

**Comment by godadom** [comment]
已解决
问题来源：存储隔离选中了学马仕

感谢！
