### ISSUE TITLE
.\local-files\resources内txt文件无法正常生效

### ISSUE THREAD

**Issue by Waitfyo** [chinosk6/gakuen-imas-localify#15]
复现流程
 git clone本仓库，git submodule update --init --recursive更新子模块；
通过imas-tools下载游戏内容文件
<img width="472" alt="image" src="https://github.com/chinosk6/gakuen-imas-localify/assets/81512208/39c50bec-ae1d-4995-9cf4-a48d7a3b8ffc">
在.\assets\gakumas-local中新建raw文件夹并把resources内的txt文件复制过去
<img width="527" alt="image" src="https://github.com/chinosk6/gakuen-imas-localify/assets/81512208/00eebed1-567c-47e4-935e-956bd3c8512f">
<img width="891" alt="image" src="https://github.com/chinosk6/gakuen-imas-localify/assets/81512208/f3ee5a23-1b4f-4131-90ec-dbc552b428fe">
在.\gakumas-local路径下运行merge.py得到合并后的resource文件
<img width="970" alt="image" src="https://github.com/chinosk6/gakuen-imas-localify/assets/81512208/0919a510-c738-4f44-92b3-74e7c53650c2">
之后编译成apk后进行测试，UI翻译基本有效，但是对于角色剧情，只有ktn第一话的翻译正常，其他翻译内容未正常生效，同时对.\local-files\resources文件进行处理，发现即使全部删除，包括adv_dear_fktn_001.txt,之后再编译成apk进行测试，发现ktn第一话的翻译仍然正常

请问是不是哪里还需要额外设置一下？

**Comment by chinosk6** [comment]
实际资源是释放到你的游戏目录内进行读取的。当你修改了资源文件后，同时修改一下 version.txt 内的内容即可。当 files 内的 version.txt 和你 apk 内的 version.txt 不一致时，才会触发资源替换。

**Comment by Waitfyo** [comment]
解决问题了，谢谢大佬

**Comment by Waitfyo** [comment]
今天玩的时候发现对话框里的内容格式好像有点问题
<img width="1037" alt="屏幕截图 2024-06-08 174813" src="https://github.com/chinosk6/gakuen-imas-localify/assets/81512208/9a468caf-cac8-4ebb-bb27-ca8de0fcb2c6">
<img width="1038" alt="屏幕截图 2024-06-08 175045" src="https://github.com/chinosk6/gakuen-imas-localify/assets/81512208/df8eb850-bbab-4830-a1fd-6e864400bbaa">
<img width="367" alt="屏幕截图 2024-06-08 162521" src="https://github.com/chinosk6/gakuen-imas-localify/assets/81512208/e831618f-3dd6-4e94-895c-015da3afbdf4">

**Comment by Badmingrams** [comment]
你更新一下子模块的代码，新版的选项样式已经调整过了

**Comment by Waitfyo** [comment]
请问是git submodule update之后重新merge，更改version.txt之后再重新打包吗，我这样弄完选项格式好像还是不对

**Comment by Badmingrams** [comment]
把子module都checkout到main分支后在子模块目录里git pull

**Comment by Waitfyo** [comment]
更新到最新的模块之后重新merge打包安装还是有问题，
<img width="780" alt="屏幕截图 2024-06-09 165812" src="https://github.com/chinosk6/gakuen-imas-localify/assets/81512208/c7569877-926c-4556-b644-a7eb095438c1">
<img width="1053" alt="屏幕截图 2024-06-09 175359" src="https://github.com/chinosk6/gakuen-imas-localify/assets/81512208/f4b51d3e-0c38-4667-8392-595f52e5c663">

**Comment by Badmingrams** [comment]
要更新依赖的版本。这个更新逻辑现在写在依赖里了，运行Makefile里面的build-resource命令会有更新依赖版本这一步。
这个逻辑其实有点问题，应该拿出来，后续版本会改进

**Comment by Waitfyo** [comment]
已解决，感谢大佬
