### ISSUE TITLE
繁體中文適配

### ISSUE THREAD

**Issue by yotv2000tw** [chinosk6/gakuen-imas-localify#29]
目前繁體中文語系地區（台灣、香港、澳門）會歸類在en當中
是否可以針對繁體中文語系進行適配？包含介面文字
另外，繁體中文（台灣）有在進行翻譯中，前面的說明頁面的翻譯人員跟倉庫訊息是否可以自行更改？
感謝。

附上fork的繁體中文插件本體倉庫：https://github.com/yotv2000tw/gakuen-imas-localify-zh-TW

**Comment by chinosk6** [comment]
在 `app/src/main/res` 目录内创建 `values-zh-rHK`, `values-zh-rMO`, `values-zh-rTW`, `values-zh-rSG` 目录，目录里面的 xml 文件和 
目前现有的 `values-zh-rCN` 一致即可，安卓会自动识别。

对应目录下的 `string.xml` 中，在 `about_contributors_asset_file` 项内会指向说明页数据 json 文件名，在 `src/main/assets` 文件夹内放入对应的文件即可。

**Comment by yotv2000tw** [comment]
> 在 `app/src/main/res` 目录内创建 `values-zh-rHK`, `values-zh-rMO`, `values-zh-rTW`, `values-zh-rSG` 目录，目录里面的 xml 文件和 目前现有的 `values-zh-rCN` 一致即可，安卓会自动识别。
> 
> 对应目录下的 `string.xml` 中，在 `about_contributors_asset_file` 项内会指向说明页数据 json 文件名，在 `src/main/assets` 文件夹内放入对应的文件即可。

了解，感謝
