### ISSUE TITLE
LSPosed和LSPatch插件相关

### ISSUE THREAD

**Issue by Bocchi0000** [chinosk6/gakuen-imas-localify#3]
我按照说明文档分别对LSPosed和LSPatch进行了测试，LSPosed可以正常加载汉化插件，但是选择LSPatch内置插件没有汉化效果

**Comment by chinosk6** [comment]
我在 LSPatch 上使用真机测试，使用本地模式，可以正常运行。
你是使用的什么环境，LSPatch 是本地模式还是便携模式呢？

**Comment by chinosk6** [comment]
我在 K50U 上面测试 LSPatch，没有问题。我这边设备的 LSPatch 版本为 0.6 (398)，安卓版本12。
能提供一下你这边的设备信息吗?

**Comment by chinosk6** [comment]
LSPatch 分支太多了，我这边不好一一适配。你试过原版 LSPatch 吗

**Comment by Bocchi0000** [comment]
好的，我使用LSPatch0.6(398)开启本地模式可以正常运行，但便携模式不加载汉化

**Comment by chinosk6** [comment]
经过测试，LSPatch 便携模式不加载汉化的原因是无法拉起插件本体获取配置。
目前做了下适配。若使用便携模式，且未安装插件本体，则使用默认配置。若使用便携模式+安装了本体，则可以正常使用。
