### ISSUE TITLE
An option to opt out of using custom fonts.

### ISSUE THREAD

**Issue by ToastyBuns3939** [chinosk6/gakuen-imas-localify#4]
It seems that the custom font included with the localify tools has some scaling issues and some unicode characters it doesn't support.
Would it be possible to have the option to opt out of using custom fonts?

![image](https://github.com/chinosk6/gakuen-imas-localify/assets/93896872/2f63167e-1e3e-4792-86ec-bb1e4cc0d00a)
![image](https://github.com/chinosk6/gakuen-imas-localify/assets/93896872/3dba5f0b-9baa-40e6-b810-0094b0e89619)
![image](https://github.com/chinosk6/gakuen-imas-localify/assets/93896872/36e06ab6-c75c-4002-9d84-d4a172efec5b)

**Comment by chinosk6** [comment]
Is there still this problem now?

**Comment by ToastyBuns3939** [comment]
> It seems that the custom font included with the localify tools has some scaling issues and some unicode characters it doesn't support.

This is no longer an issue, aside from some minor scaling issues. But yeah it would be nice to have an option to turn off the custom fonts

**Comment by chinosk6** [comment]
> This is no longer an issue, aside from some minor scaling issues. But yeah it would be nice to have an option to turn off the custom fonts

[Actions #61](../actions/runs/9529106185)
