### ISSUE TITLE
Is there any way to disable reading localization file?

### ISSUE THREAD

**Issue by yeonggille** [chinosk6/gakuen-imas-localify#43]
Hello, I hope you doing well. I was intended to use gakuenmas localify
for capturing four side view for creators, due to gakuenmas have some sort of the blur effect
similar to TAA, but it keep reading a localization file, even though it made a string JSON files empty
seems like it keep refresh the string files from .APK.
How could I stop the refreshment, and disable the localization and only using the custom graphics part?
thank you, have a good day.

**Comment by chinosk6** [comment]
You can use the new release and enable `Delete Plugin Resource` in Resource Settings.
